apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AllowedServicePortName
metadata:
  name: port-name-constraint
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Service"]
    # namespaces: ["default"]
    namespaceSelector:
      matchExpressions:
        - key: istio.io/rev
          operator: In
          values: ["asm-191-1"] 
  parameters:
    prefixes: ["http-", "http2-", "grpc-", "mongo-", "redis-", "tcp-"]
